version: 2
updates:
  # Automatic upgrade for base images used in the Dockerfile
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "docker/library/golang"
        versions: ["1.22.*"]
